### ISSUE TITLE
Update ts-auto-mock peer dependency

### ISSUE THREAD

**Issue by dome4** [Typescript-TDD/jasmine-ts-auto-mock#48]
The current version of ts-auto-mock is `2.6.5`. The problem is that the last compatible version of `ts-auto-mock` with this package `1.6.2` requires `typescript 3` which blocks me in updating my packages. Would be nice if this package could be updated :)

**Comment by uittorio** [comment]
On it! I've seen this issue so late! I will enable slack notifications for this repo as well!

**Comment by uittorio** [comment]
Hi, I've updated all the dependencies and released a new version. Note that typescript 4.0 may not work yet :)
