### ISSUE TITLE
Replace awesome-typescript-loader

### ISSUE THREAD

**Issue by dome4** [Typescript-TDD/jasmine-ts-auto-mock#49]
The package [`awesome-typescript-loader`](https://github.com/s-panferov/awesome-typescript-loader) is deprecated and should therefore be replaced. I don't have any experience with webpack but maybe replacing it with `ts-loader` should work?

(package is used in the karma-webpack example)

**Comment by uittorio** [comment]
Hi, I've updated all the dependencies and released a new version. Note that typescript 4.0 may not work yet :) I've replaced awesome-typescript-loader with ts-loader
